plugins/Page/config/routes.php
<?php
use Cake\Routing\Router;

Router::plugin('Page', function ($routes) {
    $routes->fallbacks('InflectedRoute');
});

plugins/Page/src/Model/Entity/Logo.php
<?php
namespace Page\Model\Entity; 

use Cake\ORM\Entity;

class Logo extends Entity {
	
	public function _getImgPath() {
		if (!empty($this->_properties['img'])) {
			return '/file/logo/default/' . $this->_properties['img'];
		}
	}
}
?>

plugins/Page/src/Controller/ServiceTextController.php
<?php
namespace Page\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;
use App\Lib\CmsRequest;

class ServiceTextController extends AppController {
    public function initialize() {
    	parent::initialize();

        $this->modelClass = 'Page.ServiceText';
    }

    public function index() {
        $textTable = TableRegistry::get('Page.Text');
        $blockTable = TableRegistry::get('Page.ServiceTextBlock');

        $text = $textTable
            ->find('langId')
            ->find('pageId', ['page_id' => CmsRequest::$page->id])
            ->first();

        $blocks = $blockTable
            ->find('langId')
            ->find('active')
            ->find('pageId', ['page_id' => CmsRequest::$page->id])
            ->all();

        $this->set('text', $text);
        $this->set('blocks', $blocks);
    }
}
?>

plugins/Page/src/Template/ServiceText/index.ctp
<div class="wrapper order_page">
    <div class="services_additional_block container">
        <?php foreach ($blocks as $block): ?>
            <div class="services_additional_list">
                <div class="row">
                    <div class="additional_list_text w50">
                        <div class="list_text_wrap">
                            <h3><?php echo $block->title; ?></h3>
                            <?php echo $block->text; ?>
                        </div>

                    </div>

                    <?php if ($block->img): ?>
                        <div class="additional_list_img w50" style="background-image: url(<?php echo $block->img_path; ?>);"></div>
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>